name: Pull Request Job

on:
  pull_request:
    branches:
      - main # Or any other branch where you want the job to run

jobs:
  pre-commit:
    name: Run Checks on Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Pre-Commit Checks
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.9.0
        with:
          # Configure default software
          terraform-version: 1.7.0
          args: "--all-files --color always --show-diff-on-failure"

  generate-docs:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          git-push: "true"
          git-commit-message: "docs(terraform-docs): automated action"
