name: Pull Request Job

on:
  pull_request:
    branches:
      - main # Or any other branch where you want the job to run

jobs:
  pull_request_job:
    name: Run on Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
